# Generated by Django 5.1.4 on 2025-01-18 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('family', 'Family'), ('student', 'Student')], max_length=20, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='series_posters/')),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('season', 'Season')], default='season', max_length=10)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('premium_only', models.BooleanField(default=False)),
                ('genreOne', models.ForeignKey(blank=True, default='action', on_delete=django.db.models.deletion.CASCADE, related_name='series1', to='backside.category')),
                ('genreThree', models.ForeignKey(blank=True, default='action', on_delete=django.db.models.deletion.CASCADE, related_name='series3', to='backside.category')),
                ('genreTwo', models.ForeignKey(blank=True, default='action', on_delete=django.db.models.deletion.CASCADE, related_name='series2', to='backside.category')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField(editable=False)),
                ('sub_title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('videos', models.FileField(blank=True, null=True, upload_to='anime_video/')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='backside.series')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backside.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
